INSERT INTO Class (Name) VALUES 
('Female Open'),
('Male Open'),
('50+ Female'),
('50+ Male'),
('60+ Female'),
('60+ Male'),
('70+ Female'),
('70+ Male'),
('Under 21 Female'),
('Under 21 Male'),
('Under 18 Female'),
('Under 18 Male'),
('Under 16 Female'),
('Under 16 Male'),
('Under 14 Female'),
('Under 14 Male');
