DROP TABLE IF EXISTS Arrow;
DROP TABLE IF EXISTS ShootingSession;
DROP TABLE IF EXISTS Archer;
DROP TABLE IF EXISTS Competition;
DROP TABLE IF EXISTS SubRound;
DROP TABLE IF EXISTS TargetFace;
DROP TABLE IF EXISTS Distance;
DROP TABLE IF EXISTS Division;
DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS ShootingRange;
DROP TABLE IF EXISTS Round;

CREATE TABLE Archer (
	Id INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255),
	DOB DATETIME,
	Gender VARCHAR(255),
	DefaultDivision VARCHAR(255),
	PRIMARY KEY (Id)
);

CREATE TABLE TargetFace (
	Size INT PRIMARY KEY
);

CREATE TABLE Distance (
	Dist INT PRIMARY KEY
);

CREATE TABLE ShootingRange (
	EndNo INT PRIMARY KEY
);

CREATE TABLE Division (
	Name varchar(255) NOT NULL,
	ACR varchar(255) NOT NULL,
	PRIMARY KEY (ACR)
);

CREATE TABLE Class (
	Name VARCHAR(255) NOT NULL,
	PRIMARY KEY (Name)
);


CREATE TABLE Round (
	Name VARCHAR(255),
	Equivalent VARCHAR(255) NULL,
	MaxScoreByArrow INT,
	PRIMARY KEY (Name),
	FOREIGN KEY (Equivalent) REFERENCES Round(Name)
);

CREATE TABLE SubRound (
	Dist INT,
	ShootingRange INT,
	TargetFace INT,
	RoundName VARCHAR(255),
	PRIMARY KEY (Dist, ShootingRange, TargetFace, RoundName),
	FOREIGN KEY (TargetFace) REFERENCES TargetFace(Size),
	FOREIGN KEY (Dist) REFERENCES Distance(Dist),
	FOREIGN KEY (ShootingRange) REFERENCES ShootingRange(EndNo),
	FOREIGN KEY (RoundName) REFERENCES Round(Name)
);

CREATE TABLE Competition (
	Id INT	NOT NULL AUTO_INCREMENT,
	IsChampionship BOOLEAN,
	Name VARCHAR(255),
	Duration INT,
	CompetitionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Id)
);

CREATE TABLE ShootingSession (
	Id INT NOT NULL AUTO_INCREMENT,
	ArcherId INT,
	CompetitionId INT,
	RoundName VARCHAR(255),
	Division VARCHAR(255),
	Class VARCHAR(255),
	SessionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Id),
	FOREIGN KEY (ArcherId) REFERENCES Archer(Id),
	FOREIGN KEY (CompetitionId) REFERENCES Competition(Id),
	FOREIGN KEY (Division) REFERENCES Division(ACR),
	FOREIGN KEY (RoundName) REFERENCES Round(Name)
);

CREATE TABLE Arrow (
	Id INT NOT NULL AUTO_INCREMENT,
	Dist INT,
	ShootingRange INT,
	ShootingSessionId INT,
	Score INT,
	ShootDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Id),
	FOREIGN KEY (Dist) REFERENCES Distance(Dist),
	FOREIGN KEY (ShootingRange) REFERENCES ShootingRange(EndNo),
	FOREIGN KEY (ShootingSessionId) REFERENCES ShootingSession(Id)
);
